import { baseApi } from "./baseApi";

// Common auth payload/response types

export interface User {
  id: string;
  full_name: string;
  phone: string;
  email: string;
  role: "ADMIN" | "MERCHANT" | "HUB_MANAGER" | "RIDER";
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface AuthResponse {
  success: boolean;
  data: {
    accessToken: string; // API returns camelCase
    refreshToken: string; // API returns camelCase
    user: User;
  };
  timestamp: string;
}

export interface LoginRequest {
  identifier: string;
  password: string;
}

export interface SignupRequest {
  name?: string;
  email: string;
  password: string;
}


export const authApi = baseApi.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * LOGIN
     */
    login: builder.mutation<AuthResponse, LoginRequest>({
      query: (credentials) => ({
        url: "/auth/login",
        method: "POST",
        body: credentials,
      }),
    }),

    /**
     * SIGNUP / REGISTER
     */
    signup: builder.mutation<AuthResponse, SignupRequest>({
      query: (payload) => ({
        url: "/auth/signup",
        method: "POST",
        body: payload,
      }),
    }),

    /**
     * LOGOUT (optional backend call)
     */
    logout: builder.mutation<void, void>({
      query: () => ({
        url: "/auth/logout",
        method: "POST",
      }),
    }),

    /**
     * GET CURRENT USER (optional)
     */
    getCurrentUser: builder.query<User, void>({
      query: () => ({
        url: "/auth/me",
        method: "GET",
      }),
    }),
  }),
});

// Hooks generated by RTK Query
export const {
  useLoginMutation,
  useSignupMutation,
  useLogoutMutation,
  useGetCurrentUserQuery,
} = authApi;
